name: Sync to HuggingFace hub

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF: ${{secrets.HF}}
        run: git remote add space https://huggingface.co/spaces/kubuspopolitos/demospace2
      - name: Push to hub
        env:
          HF: ${{secrets.HF}}
        run: git push --force https://huggingface.co/spaces/kubuspopolitos/demospace2 master
          

        
